name: test_package_flutter_plugin
version: 0.1.0
description: A happy flutter almost plugin being documented
homepage: https://github.com/dart-lang/dartdoc/tree/main/testing/test_package_flutter_plugin

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">2.12.0 <4.0.0"
  flutter: ">=0.1.4 <4.0.0"
